apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /home/runner/work/workbench-helm-chart/workbench-helm-chart
        containerPath: /home/runner/work/workbench-helm-chart/workbench-helm-chart
