apiVersion: v1
appVersion: "1.0"
description: A Helm chart for running the NDS Labs Workbench under Kubernetes
name: workbench
version: 1.4.0

# Dependencies for workbench. Some of the dependencies are only installed if they
# are enabled.
dependencies:
  - name: ingress-nginx
    version: ~4.1.4
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress-nginx.enabled
  - name: oauth2-proxy
    version: ~3.1.0
    repository: "https://charts.bitnami.com/bitnami"
    condition: oauth2-proxy.enabled
  - name: nfs-client-provisioner
    version: ~1.2.11
    repository: "https://supertetelman.github.io/charts/"
    condition: nfs-client-provisioner.enabled
  - name: nfs-server-provisioner
    version: ~1.4.0
    repository: "https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/"
    condition: nfs-server-provisioner.enabled
  - name: mongodb
    version: ~13.0.1
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
  - name: keycloak
    version: ~9.6.9
    repository: "https://charts.bitnami.com/bitnami"
    condition: keycloak.enabled
