
workingDirectory: ""

config:
  frontend:
    live_reload: true

controller:
  images:
    # use dev image (also enable config.frontend.live_reload)
    webui: "ndslabs/webui-livereload:develop"

  # Enable DEBUG mode for Python API (auto-restart when source updates)
  extraEnv:
    apiserver:
    - name: DEBUG
      value: "true"

  # Override frontend mountPath (default: /usr/share/nginx/html/)
  #extraVolumeMounts:
  #  webui:
  #  - mountPath: /app/                            # for live_reload
  #    name: webuisrc
  #  apiserver:
  #  - mountPath: /app/
  #    name: apisrc

  # Create volumes from the source code on the host machine
  #extraVolumes:
  #  - name: webuisrc
  #    hostPath:
  #      path: "{{ .Values.workingDirectory }}/src/webui/"         # for live_reload
  #  - name: apisrc
  #    hostPath:
  #      path: "{{ .Values.workingDirectory }}/src/apiserver/"

