{{- if .Values.mongodb.autoimport.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-import-specs"
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}-specloader
    app.kubernetes.io/component: specloader
  annotations:
{{ toYaml .Values.nodeSelector | indent 4 }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}-specloader
        app.kubernetes.io/component: specloader
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      containers:
       - name: import-specs
         image: ndslabs/specloader
         imagePullPolicy: Always
         env:
          - name: MONGO_URI
            value: "mongodb://workbench:workbench@workbench-mongodb.workbench.svc.cluster.local:27017/ndslabs?authSource=admin"
          - name: MONGO_DB
            value: "ndslabs"
          - name: GIT_REPO
            value: "http://github.com/cheese-hub/catalog"

      # TODO: Allow modifying the script by mounting at runtime?
      #  volumeMounts:
      #  - name: mongodb-setup
      #    mountPath: "/app/loadspecs.py"
      #volumes:
      #- name: mongodb-setup
      #  configMap:
      #    name: {{ .Release.Name }}-specloader
{{- end }}
