apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  frontend.json: |
    {{ .Values.config.frontend | toJson }}
  backend.json: |
    {{ .Values.config.backend | toJson }}

