apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  annotations:
    ingress.kubernetes.io/app-root: "/"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
{{ if .Values.ingress.api.annotations | default false }}
    {{ toYaml .Values.ingress.api.annotations | nindent 4 }}
{{ end }}
spec:
{{ if .Values.ingress.class | default false }}
  ingressClassName: {{ .Values.ingress.class }}
{{ end }}
{{ if .Values.ingress.tls | default false }}
  tls:
    {{ toYaml .Values.ingress.tls | nindent 4 }}
{{ end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port: 
              number: 5000
{{ with .Values.ingress.api.extraRules }}
  {{ toYaml . | nindent 2 }}
{{ end }}
