apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-webui
  namespace: {{ .Release.Namespace }}
  annotations:
    ingress.kubernetes.io/app-root: "/"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    {{ toYaml .Values.ingress.webui.annotations | nindent 4 }}
spec:
{{ if .Values.ingress.class | default false }}
  ingressClassName: {{ .Values.ingress.class }}
{{ end }}
{{ if .Values.ingress.tls | default false }}
  tls:
    {{ toYaml .Values.ingress.tls | nindent 4  }}
{{ end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 80
