apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  annotations:
{{ toYaml .Values.ingress.api.annotations | indent 4 }}
spec:
{{ if .Values.ingress.tls | default false }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{ end }}
  rules:
  - host: {{ .Values.config.backend.domain }}
    http:
      paths:
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port: 
              number: 5000
