apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: {{ .Release.Name }}
{{- with .Values.controller.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  selector:
    component: {{ .Release.Name }}
{{- with .Values.controller.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
  ports:
    - port: 80
      name: webui
      protocol: TCP
    - port: 5000
      name: api
      protocol: TCP
