apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Release.Name }}
{{- with .Values.controller.serviceLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Release.Name }}
{{- with .Values.controller.extraLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
  ports:
    - port: 80
      targetPort: webui
      name: webui
      protocol: TCP
    - port: 5000
      targetPort: api
      name: api
      protocol: TCP
