{{- if .Values.controller.serviceAccount }}
{{- if .Values.controller.serviceAccount.create | default true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.serviceAccount.name | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
