name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Add dependency helm repos 
        run: |
          helm repo add oauth2-proxy https://charts.bitnami.com/bitnami
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add nfs-client-provisioner https://supertetelman.github.io/charts
          helm repo add nfs-server-provisioner https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner
          helm repo add mongodb https://charts.bitnami.com/bitnami
          helm repo add keycloak https://charts.bitnami.com/bitnami
          helm repo update

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config values.localdev.yaml --chart-dirs . --charts . --chart-repos oauth2-proxy=https://charts.bitnami.com/bitnami ingress-nginx=https://kubernetes.github.io nfs-client-provisioner=https://supertetelman.github.io/charts nfs-server-provisioner=https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner mongodb=https://charts.bitnami.com/bitnami keycloak=https://charts.bitnami.com/bitnami
