name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      #- name: Add dependency helm repos 
      #  run: |
      #    helm repo add oauth2-proxy https://charts.bitnami.com/bitnami
      #    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      #    helm repo add nfs-client-provisioner https://supertetelman.github.io/charts
      #    helm repo add nfs-server-provisioner https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner
      #    helm repo add mongodb https://charts.bitnami.com/bitnami
      #    helm repo add keycloak https://charts.bitnami.com/bitnami
      #    helm repo update

      #- uses: actions/setup-python@v4
      #  with:
      #    python-version: '3.9'
      #    check-latest: true

      #- name: Set up chart-testing
      #  uses: helm/chart-testing-action@v2.3.1

      #- name: Run chart-testing (list-changed)
      #  id: list-changed
      #  run: |
      #    changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
      #    if [[ -n "$changed" ]]; then
      #      echo "::set-output name=changed::true"
      #    fi

      #- name: Run chart-testing (lint)
      #  run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Run helm lint
        run: |
          helm version
          helm lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0

      - name: Create namespace + imported Keycloak realm (workbench-dev)
        run: |
          kubectl create namespace customnamespace
          kubectl create configmap keycloak-realm -n customnamespace --from-file=realm.json

      - name: Fetch dependency helm charts
        run: |
          helm dep up

      - name: Run helm install (localdev)
        run: |
          helm upgrade --install -n customnamespace customreleasename . -f values.localdev.yaml -f values.realmimport.yaml

      - name: Check for available StorageClasses
        run: kubectl get sc

      - name: Check pod labels
        run: kubectl get pods -n customnamespace --show-labels

      - name: Wait for NFS Server to start
        run: kubectl wait pods -n customnamespace -lapp.kubernetes.io/component=nfs-server-provisioner --for condition=Ready --timeout=90s

      - name: Wait for Postgres + Keycloak to start
        run: |
          kubectl wait pods -n customnamespace -lapp.kubernetes.io/component=primary --for condition=Ready --timeout=90s
          kubectl wait pods -n customnamespace -lapp.kubernetes.io/component=keycloak --for condition=Ready --timeout=90s

      - name: Wait for Redis + OAuth2 Proxy to start
        run: |
          kubectl wait pods -n customnamespace -lapp.kubernetes.io/component=master --for condition=Ready --timeout=90s
          kubectl wait pods -n customnamespace -lapp.kubernetes.io/component=oauth2-proxy --for condition=Ready --timeout=90s

      - name: Wait for MongoDB + Workbench to start
        run: |
          kubectl wait pods -n customnamespace -lapp.kubernetes.io/component=mongodb --for condition=Ready --timeout=90s
          kubectl wait pods -n customnamespace -lapp.kubernetes.io/component=customreleasename --for condition=Ready --timeout=90s
