name: Smoke Test

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Run helm lint
        run: |
          helm version
          helm lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0

      - name: Create namespace + imported Keycloak realm (workbench-dev)
        run: |
          kubectl create namespace customnamespace
          kubectl create configmap keycloak-realm -n customnamespace --from-file=realm.json

      - name: Run helm install (localdev)
        run: |
          helm dep up
          helm upgrade --install -n customnamespace customreleasename . -f values.localdev.yaml -f values.realmimport.yaml --set nfs-server-provisioner.persistence.storageClass=standard --set mongodb.global.storageClass=standard --set oauth2-proxy.global.storageClass=standard --set keycloak.global.storageClass=standard

      - name: Wait for NFS Server to start
        run: |
          kubectl wait pods -n customnamespace -lapp=nfs-server-provisioner --for condition=Ready --timeout=90s || kubectl describe pod -lapp=nfs-server-provisioner -n customnamespace && kubectl logs -lapp=nfs-server-provisioner -n customnamespace
          kubectl get pods -n customnamespace

      - name: Wait for Postgres + Keycloak to start
        run: |
          kubectl wait pods -n customnamespace -lapp.kubernetes.io/component=primary --for condition=Ready --timeout=90s || kubectl describe pods -lapp.kubernetes.io/component=primary -n customnamespace && kubectl logs -lapp.kubernetes.io/component=primary -n customnamespace
          kubectl get pods -n customnamespace
          kubectl wait pods -n customnamespace -lapp.kubernetes.io/component=keycloak --for condition=Ready --timeout=300s || kubectl describe pods -lapp.kubernetes.io/component=keycloak -n customnamespace && kubectl logs -lapp.kubernetes.io/component=keycloak -n customnamespace
          kubectl get pods -n customnamespace

      - name: Wait for Redis + OAuth2 Proxy to start
        run: |
          kubectl wait pods -n customnamespace -lapp.kubernetes.io/component=master --for condition=Ready --timeout=90s || kubectl describe pod -lapp.kubernetes.io/component=master -n customnamespace && kubectl logs -lapp.kubernetes.io/component=master -n customnamespace
          kubectl get pods -n customnamespace
          kubectl wait pods -n customnamespace -lapp.kubernetes.io/component=oauth2-proxy --for condition=Ready --timeout=300s || kubectl describe pod -lapp.kubernetes.io/component=oauth2-proxy -n customnamespace && kubectl logs -lapp.kubernetes.io/component=oauth2-proxy -n customnamespace -c wait-for-keycloak && kubectl logs -lapp.kubernetes.io/component=oauth2-proxy -n customnamespace
          kubectl get pods -n customnamespace

      - name: Wait for MongoDB + Workbench to start
        run: |
          kubectl wait pods -n customnamespace -lapp.kubernetes.io/component=mongodb --for condition=Ready --timeout=90s || kubectl describe pod -lapp.kubernetes.io/component=mongodb -n customnamespace && kubectl logs -lapp.kubernetes.io/component=mongodb -n customnamespace
          kubectl get pods -n customnamespace
          kubectl wait pods -n customnamespace -lapp.kubernetes.io/component=customreleasename --for condition=Ready --timeout=300s || kubectl describe pod -lapp.kubernetes.io/component=customreleasename -n customnamespace && kubectl logs -lapp.kubernetes.io/component=customreleasename -n customnamespace -c wait-for-keycloak && kubectl logs -lapp.kubernetes.io/component=customreleasename-n customnamespace
          kubectl get pods -n customnamespace
