name: Smoke Test

on: 
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Fetch helm chart dependencies
        run: |
          helm dep up

      - name: Run helm lint
        run: |
          helm lint

  dev-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0

      - name: Setup environment
        run: |
          cat .env | sed -e 's/WHICH_ARGS=-s/WHICH_ARGS=/' -e 's/REALM_IMPORT=true/REALM_IMPORT=false/' -e "s/KUBE_CONTEXT=docker-desktop/KUBE_CONTEXT=$(kubectl config current-context)/" > .env
          cat .env

      - name: Output Helm chart templates (for debugging)
        run: |
          make dep
          helm template --debug --dry-run workbench -n workbench . -f values.localdev.yaml -f values.ci.yaml -f values.localdev.livereload.yaml --set workingDirectory="${PWD}"

      - name: Clone repos, compile source, fetch deps, and install (localdev + ci + livereload)
        run: |
          make dep
          make clone
          make compile
          helm upgrade --debug --install workbench -n workbench . --create-namespace -f values.localdev.yaml -f values.ci.yaml -f values.localdev.livereload.yaml --set workingDirectory="${PWD}"

      - name: Wait for Workbench Startup
        uses: nds-org/workbench-helm-chart/.github/workflows/wait-for-start.yml@autobuild-webui-livereload-image

      - name: Show Workbench status
        run: |
          make status

      - name: Describe Workbench Pod (view Pod events)
        run: |
          make describe

      - name: Rebuild Docker images
        run: |
          make build

      - name: Restart Workbench Pod
        run: |
          make restart

      - name: Run make uninstall
        run: |
          make uninstall

      - name: Run make clean
        run: |
          make clean

      - name: Run make clean_all
        run: |
          make clean_all

  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Fetch helm chart dependencies
        run: |
          helm dep up

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0

      - name: Run helm template (localdev + ci)
        run: |
          helm template -n workbench workbench . -f values.localdev.yaml -f values.ci.yaml --debug --dry-run

      - name: Run helm install (localdev + ci)
        run: |
          helm upgrade --install -n workbench workbench . --create-namespace -f values.localdev.yaml -f values.ci.yaml --debug

      - name: Wait for Workbench Startup
        uses: nds-org/workbench-helm-chart/.github/workflows/wait-for-start.yml@autobuild-webui-livereload-image

      - name: "Cleanup: Uninstall Helm release"
        if: ${{ always() }}
        run: |
          helm uninstall workbench -n workbench

      - name: "Cleanup: Delete namespace"
        if: ${{ always() }}
        run: |
          kubectl delete namespace workbench
